version: '3.3'

services: 
  postgres:
    image: postgres:13 
    container_name: postgres
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports: 
      - '5432:5432'
    volumes: 
      - ./database:/var/lib/postgresql/data

  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - ./database:/var/lib/pgadmin
    depends_on: 
      - postgres

  mysql:
    image: mysql:5
    platform: linux/x86_64
    container_name: mysql
    environment:
      - MYSQL_DATABASE=store_db
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
    volumes:
      - ./database:/var/lib/phpmyadmin
    depends_on:
      - mysql